!manual()
table Top50IMDBMovies
  [name] = NA
  [author] = NA
  [genre] = NA
  [rank] = NA
  [date] = NA
override
  [name],[author],[genre],[rank],[date]
  "The Shawshank Redemption","Frank Darabont","Drama","1","1994"
  "The Godfather","Francis Ford Coppola","Crime, Drama","2","1972"
  "The Dark Knight","Christopher Nolan","Action, Crime, Drama","3","2008"
  "The Godfather: Part II","Francis Ford Coppola","Crime, Drama","4","1974"
  "12 Angry Men","Sidney Lumet","Crime, Drama","5","1957"
  "Schindler''s List","Steven Spielberg","Biography, Drama, History","6","1993"
  "The Lord of the Rings: The Return of the King","Peter Jackson","Action, Adventure, Drama","7","2003"
  "Pulp Fiction","Quentin Tarantino","Crime, Drama","8","1994"
  "The Good, the Bad and the Ugly","Sergio Leone","Western","9","1966"
  "The Lord of the Rings: The Fellowship of the Ring","Peter Jackson","Action, Adventure, Drama","10","2001"
  "Fight Club","David Fincher","Drama","11","1999"
  "Forrest Gump","Robert Zemeckis","Drama, Romance","12","1994"
  "Inception","Christopher Nolan","Action, Adventure, Sci-Fi","13","2010"
  "The Lord of the Rings: The Two Towers","Peter Jackson","Action, Adventure, Drama","14","2002"
  "Star Wars: Episode V - The Empire Strikes Back","Irvin Kershner","Action, Adventure, Fantasy","15","1980"
  "The Matrix","Lana Wachowski, Lilly Wachowski","Action, Sci-Fi","16","1999"
  "Goodfellas","Martin Scorsese","Biography, Crime, Drama","17","1990"
  "One Flew Over the Cuckoo''s Nest","Miloš Forman","Drama","18","1975"
  "Seven Samurai","Akira Kurosawa","Action, Adventure, Drama","19","1954"
  "Se7en","David Fincher","Crime, Drama, Mystery","20","1995"
  "Life Is Beautiful","Roberto Benigni","Comedy, Drama, Romance","21","1997"
  "City of God","Fernando Meirelles, Kátia Lund","Crime, Drama","22","2002"
  "The Silence of the Lambs","Jonathan Demme","Crime, Drama, Thriller","23","1991"
  "It''s a Wonderful Life","Frank Capra","Drama, Family, Fantasy","24","1946"
  "Star Wars: Episode IV - A New Hope","George Lucas","Action, Adventure, Fantasy","25","1977"
  "Saving Private Ryan","Steven Spielberg","Drama, War","26","1998"
  "Spirited Away","Hayao Miyazaki","Animation, Adventure, Family","27","2001"
  "The Green Mile","Frank Darabont","Crime, Drama, Fantasy","28","1999"
  "Parasite","Bong Joon Ho","Comedy, Drama, Thriller","29","2019"
  "Interstellar","Christopher Nolan","Adventure, Drama, Sci-Fi","30","2014"
  "Léon: The Professional","Luc Besson","Action, Crime, Drama","31","1994"
  "The Usual Suspects","Bryan Singer","Crime, Drama, Mystery","32","1995"
  "Harakiri","Masaki Kobayashi","Action, Drama, Mystery","33","1962"
  "The Lion King","Roger Allers, Rob Minkoff","Animation, Adventure, Drama","34","1994"
  "Back to the Future","Robert Zemeckis","Adventure, Comedy, Sci-Fi","35","1985"
  "The Pianist","Roman Polanski","Biography, Drama, Music","36","2002"
  "Terminator 2: Judgment Day","James Cameron","Action, Sci-Fi","37","1991"
  "American History X","Tony Kaye","Drama","38","1998"
  "Modern Times","Charlie Chaplin","Comedy, Drama, Family","39","1936"
  "Psycho","Alfred Hitchcock","Horror, Mystery, Thriller","40","1960"
  "Gladiator","Ridley Scott","Action, Adventure, Drama","41","2000"
  "City Lights","Charlie Chaplin","Comedy, Drama, Romance","42","1931"
  "The Departed","Martin Scorsese","Crime, Drama, Thriller","43","2006"
  "The Intouchables","Olivier Nakache, Éric Toledano","Biography, Comedy, Drama","44","2011"
  "Whiplash","Damien Chazelle","Drama, Music","45","2014"
  "The Prestige","Christopher Nolan","Drama, Mystery, Sci-Fi","46","2006"
  "The Lion King","Roger Allers, Rob Minkoff","Animation, Adventure, Drama","47","1994"
  "Apocalypse Now","Francis Ford Coppola","Drama, War","48","1979"
  "Alien","Ridley Scott","Horror, Sci-Fi","49","1979"
  "Sunset Boulevard","Billy Wilder","Drama, Film-Noir","50","1950"
