nodeLinker: node-modules

npmScopes:
  deltix:
    npmAlwaysAuth: true
    npmAuthIdent: '${NPM_USER}:${NEXUS_PASS}'
    npmRegistryServer: 'https://nexus.deltixhub.com/repository/epm-rtc-npm/'

yarnPath: .yarn/releases/yarn-4.9.4.cjs
