include:
  - project: Gitlab/ci
    ref: 3.0.6
    file: jobs/cloud-auth/aws.gitlab-ci.yml

  - local: "ci/test_qgbot.yml"
  - local: "ci/store_results_to_s3.yml"
  - local: "ci/build_frontend.yml"
  - local: "ci/e2e_frontend.yml"

.sed_template: &sed_template |
  sed -i -E 's@^URIs:.+ubuntu\.com.+@URIs: http://ftp.uni-stuttgart.de/ubuntu/@' /etc/apt/sources.list.d/ubuntu.sources

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      allow_failure: true
    - if: '$CI_PIPELINE_SOURCE  == "schedule"'
      when: always
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
      auto_cancel:
        on_new_commit: interruptible
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - if: $CI_COMMIT_BRANCH == "stable" && $CI_COMMIT_MESSAGE !~ /^RobotBuild/
      when: always
    - if: $CI_COMMIT_TAG

stages:
  - prepare # semver tag on stable branch
  - build # Application build
  - publish # publush docker images
  - deploy # deploy application to k8s
  - post-deploy # startup checks
  - e2e-test # run e2e tests
  - aggregate_results # combine test results from several runners and publish it
  - promote # copy docker image to public repo

variables:
  TOOLS_IMAGE: "registry.deltixhub.com/devops/kubernetes-tools-aws:1.32.0"
  VERBOSE: ${VERBOSE:-false}
  ATOMIC: "true" # Unset or use `null` to disable atomic option for helm upgrade, e.g. ATOMIC: "" in GitLab variables
  SECRET: "true"
  DOCKER_REGISTRY_USER: ${NEXUS_USER}
  DOCKER_REGISTRY_PASS: ${NEXUS_PASS}
  DOCKER_REGISTRY_SERVER: "registry-dev.deltixhub.com"

  ARTIFACTORY_DOCKER_PATH_FRONTEND: "deltix.docker/quantgrid/frontend"
  ARTIFACTORY_DOCKER_PATH_BACKEND: "deltix.docker/quantgrid/backend"
  ARTIFACTORY_DOCKER_PATH_DESTINATION_DIAL: "deltix.docker/quantgrid/destination-dial"
  ARTIFACTORY_DOCKER_PATH_SOURCE_DIAL: "deltix.docker/quantgrid/source-dial"
  ARTIFACTORY_DOCKER_PATH_QGBOT: "deltix.docker/quantgrid/qgbot"

  REVIEW_URL: "https://xl-ai-dial-xl-mr-${CI_MERGE_REQUEST_IID}.gke.test.dial.parts"
  REVIEW_DIAL_URL: "https://core-ai-dial-xl-mr-${CI_MERGE_REQUEST_IID}.gke.test.dial.parts"

default:
  retry:
    max: 2
    when: runner_system_failure

# allows to use image form dev registry instead of building first image.
check_existing_branch_tag:
  image: ${TOOLS_IMAGE}
  stage: publish
  script:
    - 'TAG_EXISTS_QGBOT=$(curl -sSL -u $ARTIFACTORY_TEST_USER:$ARTIFACTORY_TEST_PASS "https://artifactory.epam.com:6155/artifactory/api/docker/epm-rtc-test-docker/v2/deltix.docker/quantgrid/qgbot/manifests/$CI_COMMIT_REF_SLUG" | jq -r .tag)'
    - |
      if [[ $TAG_EXISTS_QGBOT == $CI_COMMIT_REF_SLUG ]]; then
        echo "Tag '$CI_COMMIT_REF_SLUG' exists for image '$ARTIFACTORY_DOCKER_PATH_QGBOT'."
      else
        echo "Tag '$CI_COMMIT_REF_SLUG' does NOT exist for image '$ARTIFACTORY_DOCKER_PATH_QGBOT'."
        curl -X POST -sSf -u $ARTIFACTORY_USER:$ARTIFACTORY_PASS "https://artifactory.epam.com/artifactory/api/copy/epm-rtc-docker/deltix.docker/quantgrid/qgbot/main?to=/epm-rtc-test-docker/deltix.docker/quantgrid/qgbot/$CI_COMMIT_REF_SLUG"
      fi
    - 'TAG_EXISTS_FRONTEND=$(curl -sSL -u $ARTIFACTORY_TEST_USER:$ARTIFACTORY_TEST_PASS "https://artifactory.epam.com:6155/artifactory/api/docker/epm-rtc-test-docker/v2/deltix.docker/quantgrid/frontend/manifests/$CI_COMMIT_REF_SLUG" | jq -r .tag)'
    - |
      if [[ $TAG_EXISTS_FRONTEND == $CI_COMMIT_REF_SLUG ]]; then
        echo "Tag '$CI_COMMIT_REF_SLUG' exists for image '$ARTIFACTORY_DOCKER_PATH_FRONTEND'."
      else
        echo "Tag '$CI_COMMIT_REF_SLUG' does NOT exist for image '$ARTIFACTORY_DOCKER_PATH_FRONTEND'."
        curl -X POST -sSf -u $ARTIFACTORY_USER:$ARTIFACTORY_PASS "https://artifactory.epam.com/artifactory/api/copy/epm-rtc-docker/deltix.docker/quantgrid/frontend/main?to=/epm-rtc-test-docker/deltix.docker/quantgrid/frontend/$CI_COMMIT_REF_SLUG"
      fi
    - 'TAG_EXISTS_BACKEND=$(curl -sSL -u $ARTIFACTORY_TEST_USER:$ARTIFACTORY_TEST_PASS "https://artifactory.epam.com:6155/artifactory/api/docker/epm-rtc-test-docker/v2/deltix.docker/quantgrid/backend/manifests/$CI_COMMIT_REF_SLUG" | jq -r .tag)'
    - |
      if [[ $TAG_EXISTS_BACKEND == $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME ]]; then
        echo "Tag '$CI_COMMIT_REF_SLUG' exists for image '$ARTIFACTORY_DOCKER_PATH_BACKEND'."
      else
        echo "Tag '$CI_COMMIT_REF_SLUG' does NOT exist for image '$ARTIFACTORY_DOCKER_PATH_BACKEND'."
        curl -X POST -sSf -u $ARTIFACTORY_USER:$ARTIFACTORY_PASS "https://artifactory.epam.com/artifactory/api/copy/epm-rtc-docker/deltix.docker/quantgrid/backend/main?to=/epm-rtc-test-docker/deltix.docker/quantgrid/backend/$CI_COMMIT_REF_SLUG"
      fi
    - 'TAG_EXISTS_BACKEND=$(curl -sSL -u $ARTIFACTORY_TEST_USER:$ARTIFACTORY_TEST_PASS "https://artifactory.epam.com:6155/artifactory/api/docker/epm-rtc-test-docker/v2/deltix.docker/quantgrid/destination-dial/manifests/$CI_COMMIT_REF_SLUG" | jq -r .tag)'
    - |
      if [[ $TAG_EXISTS_BACKEND == $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME ]]; then
        echo "Tag '$CI_COMMIT_REF_SLUG' exists for image '$ARTIFACTORY_DOCKER_PATH_DESTINATION_DIAL'."
      else
        echo "Tag '$CI_COMMIT_REF_SLUG' does NOT exist for image '$ARTIFACTORY_DOCKER_PATH_DESTINATION_DIAL'."
        curl -X POST -sSf -u $ARTIFACTORY_USER:$ARTIFACTORY_PASS "https://artifactory.epam.com/artifactory/api/copy/epm-rtc-docker/deltix.docker/quantgrid/destination-dial/main?to=/epm-rtc-test-docker/deltix.docker/quantgrid/destination-dial/$CI_COMMIT_REF_SLUG"
      fi
    - 'TAG_EXISTS_BACKEND=$(curl -sSL -u $ARTIFACTORY_TEST_USER:$ARTIFACTORY_TEST_PASS "https://artifactory.epam.com:6155/artifactory/api/docker/epm-rtc-test-docker/v2/deltix.docker/quantgrid/source-dial/manifests/$CI_COMMIT_REF_SLUG" | jq -r .tag)'
    - |
      if [[ $TAG_EXISTS_BACKEND == $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME ]]; then
        echo "Tag '$CI_COMMIT_REF_SLUG' exists for image '$ARTIFACTORY_DOCKER_PATH_SOURCE_DIAL'."
      else
        echo "Tag '$CI_COMMIT_REF_SLUG' does NOT exist for image '$ARTIFACTORY_DOCKER_PATH_SOURCE_DIAL'."
        curl -X POST -sSf -u $ARTIFACTORY_USER:$ARTIFACTORY_PASS "https://artifactory.epam.com/artifactory/api/copy/epm-rtc-docker/deltix.docker/quantgrid/source-dial/main?to=/epm-rtc-test-docker/deltix.docker/quantgrid/source-dial/$CI_COMMIT_REF_SLUG"
      fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  interruptible: true
  tags:
    - epam

########################################### trigger to deploy review env section ##############################################

trigger_deploy_review_environment:
  stage: deploy
  variables:
    MERGE_REQUEST_IID: mr-${CI_MERGE_REQUEST_IID}
    REVIEW_IMAGE_TAG: $CI_COMMIT_REF_SLUG
  inherit:
    variables: false
  needs:
    - job: check_existing_branch_tag
    - job: publish_frontend
      optional: true
    - job: publish_backend
      optional: true
    - job: publish_destination_dial
      optional: true
    - job: publish_source_dial
      optional: true
    - job: publish_qgbot
      optional: true
  trigger:
    project: Clients/dial/test/dial-review/dial-xl
    branch: version-3  # TODO: DELETE THIS!!!
    strategy: depend
    inputs:
      gitlab_merge_request_iid: ${MERGE_REQUEST_IID}
      review_image_tag: ${REVIEW_IMAGE_TAG}
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

###############################################################################################################################


########################################### deploy to development env section #################################################

trigger_deploy_development_frontend:
  stage: deploy
  inherit:
    variables: false
  needs:
    - publish_frontend
    - publish_destination_dial
    - publish_source_dial
  trigger:
    project: Clients/dial/dev/dial-xl/dial-xl-frontend
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

trigger_deploy_development_backend:
  stage: deploy
  inherit:
    variables: false
  needs:
    - publish_backend
    - publish_destination_dial
    - publish_source_dial
  trigger:
    project: Clients/dial/dev/dial-xl/dial-xl-backend
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

trigger_deploy_development_bot:
  stage: deploy
  inherit:
    variables: false
  needs:
    - job: publish_qgbot
  trigger:
    project: Clients/dial/dev/dial-xl/expressive-logic-agent
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

###############################################################################################################################

### Increment patch version of previous tag. Run on commit to stable branch
"Tag branch":
  image: alpine/git:v2.32.0
  stage: prepare
  script:
    - ver=$(git describe --abbrev=0 --tags | cut -f-2 -d '.') || ver=0.0
    - minor_tag=$(git describe --abbrev=0 --tags | cut -f 3 -d '.') || minor_tag=0
    - release_tag=${ver}.$(( minor_tag+1 ))
    - git remote set-url origin https://$GITLAB_ROBOT_NAME:$GITLAB_ROBOT_PUSH_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
    - git config user.name $GITLAB_ROBOT_NAME
    - git config user.email ${GITLAB_ROBOT_EMAIL}
    - git diff --quiet && git diff --staged --quiet || git commit -am "RobotBuild ${release_tag}"
    - git tag ${release_tag}
    - git push origin HEAD:${CI_COMMIT_REF_NAME} --tags
  dependencies: [ ]
  rules:
    - if: $CI_COMMIT_BRANCH == "stable" && $CI_COMMIT_MESSAGE !~ /^RobotBuild/
  tags:
    - kubernetes

### Build backend application (jar). Run on commit to all tags or branches except stable
build_backend:
  stage: build
  image: eclipse-temurin:17-jdk
  variables:
    GRADLE_CACHE_KEY: "1" # increase when bumping gradle/major dependency versions
  # Overwrite Gradle cache directory.
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    # Note: with "--continue" option Gradle will execute tests for all projects
    - *sed_template
    - apt update
    - apt install -y python3-pip
    - python3 --version
    - ./gradlew build
  artifacts:
    when: always
    paths:
      - backend/engine/build/reports/
      - backend/common/build/reports/
      - backend/parser/build/reports/
      - backend/proto/build/reports/
      - backend/web/build/distributions/qg-*.tar
      - backend/web/build/reports/
      - airbyte-integrations/destination/build/libs/*.jar
      - airbyte-integrations/source/build/libs/*.jar
    reports:
      junit:
        - backend/engine/build/test-results/test/**/TEST-*.xml
        - backend/common/build/test-results/test/**/TEST-*.xml
        - backend/parser/build/test-results/test/**/TEST-*.xml
        - backend/proto/build/test-results/test/**/TEST-*.xml
        - backend/web/build/test-results/test/**/TEST-*.xml
  cache:
    key: "$GRADLE_CACHE_KEY"
    paths:
      - .gradle/wrapper
      - .gradle/caches
    policy: pull-push
  tags:
    - Linux
    - DockerExecutor
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - backend/**/*
          - infrastructure/**/*
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH  == "main"
  interruptible: true

# lint for qgbot
lint_qgbot:
  image: python:3.12-slim
  stage: build
  before_script:
    - apt-get update && apt-get install -y make
  script:
    - pip install poetry==2.3.1
    - cd ./python/assistant
    - make lint
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
      changes:
        paths:
          - python/**/*
          - infrastructure/**/*
    - if: $CI_COMMIT_BRANCH  == "main"
    - if: $CI_COMMIT_TAG
  tags:
    - kubernetes

### CI template for build docker images
.publish_template:
  image: public.ecr.aws/docker/library/docker:27.3-cli # change dockerhub.deltixhub.com/docker:23.0.6 to avoid limit hit
  stage: publish
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_BUILD_ARGS: ""
  services:
    - docker:23.0.6-dind
  before_script:
    - mkdir -p $HOME/.docker
    # Use DOCKER_AUTH_CONFIG for login to deltix repo
    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  script:
    - docker build $DOCKER_BUILD_ARGS -t ${REPOSITORY}/${ARTIFACTORY_DOCKER_PATH}:${DOCKER_TAG} -f ${DOCKERFILE_PATH} .
    - docker push ${REPOSITORY}/${ARTIFACTORY_DOCKER_PATH}:${DOCKER_TAG}
  cache: { }
  tags:
    - Linux
    - DockerExecutor
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_TEST_REPOSITORY}
    - if: $CI_COMMIT_TAG
      variables:
        DOCKER_TAG: ${CI_COMMIT_TAG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_DEV_REPOSITORY}
    - if: $CI_COMMIT_BRANCH  == "main"
      variables:
        DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_DEV_REPOSITORY}
  interruptible: true

### Build backend docker and push to artifactory. Extend ".publish_template" job
publish_backend:
  extends: .publish_template
  variables:
    ARTIFACTORY_DOCKER_PATH: ${ARTIFACTORY_DOCKER_PATH_BACKEND}
    DOCKERFILE_PATH: "infrastructure/backend_cluster/Dockerfile"
  needs:
    - build_backend
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_TEST_REPOSITORY}
      changes:
        paths:
          - backend/**/*
          - infrastructure/**/*
    - if: $CI_COMMIT_TAG
      variables:
        DOCKER_TAG: ${CI_COMMIT_TAG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_DEV_REPOSITORY}
    - if: $CI_COMMIT_BRANCH  == "main"
      variables:
        DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_DEV_REPOSITORY}

### Build frontend docker and push to artifactory. Extend ".publish_template" job
publish_frontend:
  extends: .publish_template
  variables:
    ARTIFACTORY_DOCKER_PATH: ${ARTIFACTORY_DOCKER_PATH_FRONTEND}
    DOCKERFILE_PATH: "infrastructure/frontend/Dockerfile"
  needs:
    - build_frontend
    - test_frontend
    - format_frontend
    - lint_frontend
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_TEST_REPOSITORY}
        # DOCKER_BUILD_ARGS:
        #   Pass build-time args that become ENV vars in the image (ARG->ENV in Dockerfile).
        #   The entrypoint will envsubst() these into nginx.conf.template at container start

        # CORE_HOST:
        #   Internal Kubernetes “core” service address.
        DOCKER_BUILD_ARGS: >
          --build-arg CORE_HOST=dial-core.dial.svc.cluster.local

      changes:
        paths:
          - frontend/**/*
          - infrastructure/**/*
          - backend/parser/src/main/antlr/com/epam/deltix/quantgrid/parser/**/*
    - if: $CI_COMMIT_TAG
      variables:
        DOCKER_TAG: ${CI_COMMIT_TAG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_DEV_REPOSITORY}
    - if: $CI_COMMIT_BRANCH  == "main"
      variables:
        DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_DEV_REPOSITORY}
        # CORE_HOST: Static upstream host for the core service. To be updated regarding env.
        DOCKER_BUILD_ARGS: >
          --build-arg CORE_HOST=dial-core.dial.svc.cluster.local

### Build airbyte destination dial docker and push to artifactory. Extend ".publish_template" job
publish_destination_dial:
  extends: .publish_template
  variables:
    ARTIFACTORY_DOCKER_PATH: ${ARTIFACTORY_DOCKER_PATH_DESTINATION_DIAL}
    DOCKERFILE_PATH: "infrastructure/airbyte_integrations/destination/Dockerfile"
  needs:
    - build_backend
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_TEST_REPOSITORY}
      changes:
        paths:
          - airbyte-integrations/destination/**/*
    - if: $CI_COMMIT_TAG
      variables:
        DOCKER_TAG: ${CI_COMMIT_TAG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_DEV_REPOSITORY}
    - if: $CI_COMMIT_BRANCH  == "main"
      variables:
        DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_DEV_REPOSITORY}

### Build airbyte source dial docker and push to artifactory. Extend ".publish_template" job
publish_source_dial:
  extends: .publish_template
  variables:
    ARTIFACTORY_DOCKER_PATH: ${ARTIFACTORY_DOCKER_PATH_SOURCE_DIAL}
    DOCKERFILE_PATH: "infrastructure/airbyte_integrations/source/Dockerfile"
  needs:
    - build_backend
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_TEST_REPOSITORY}
      changes:
        paths:
          - airbyte-integrations/source/**/*
    - if: $CI_COMMIT_TAG
      variables:
        DOCKER_TAG: ${CI_COMMIT_TAG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_DEV_REPOSITORY}
    - if: $CI_COMMIT_BRANCH  == "main"
      variables:
        DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_DEV_REPOSITORY}

### Build qgbot docker and push to artifactory.
publish_qgbot:
  image: public.ecr.aws/docker/library/docker:27.3-cli # change dockerhub.deltixhub.com/docker:23.0.6 to avoid limit hit
  stage: publish
  needs:
    - job: lint_qgbot
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  cache: { }
  services:
    - docker:23.0.6-dind
  before_script:
    - mkdir -p $HOME/.docker
    # Use DOCKER_AUTH_CONFIG for login to deltix repo
    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
  script:
    - cp ./backend/proto/src/main/proto/api.proto ./python/
    - imageUrl=$REPOSITORY/${DOCKER_PATH}
    - docker build -t $imageUrl:${DOCKER_TAG} -t $imageUrl:${DOCKER_ADDITIONAL_TAG} -f ${DOCKERFILE_PATH} ./python/
    - docker push $imageUrl:${DOCKER_TAG}
    - docker push $imageUrl:${DOCKER_ADDITIONAL_TAG}
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        DOCKER_PATH: ${ARTIFACTORY_DOCKER_PATH_QGBOT}
        DOCKER_TAG: ${CI_COMMIT_TAG}
        DOCKER_ADDITIONAL_TAG: latest
        REPOSITORY: ${ARTIFACTORY_DOCKER_DEV_REPOSITORY}
        DOCKERFILE_PATH: "python/Dockerfile"
    - if: $CI_COMMIT_BRANCH  == "main"
      variables:
        DOCKER_PATH: ${ARTIFACTORY_DOCKER_PATH_QGBOT}
        DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
        DOCKER_ADDITIONAL_TAG: alpha
        REPOSITORY: ${ARTIFACTORY_DOCKER_DEV_REPOSITORY}
        DOCKERFILE_PATH: "python/Dockerfile"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        DOCKER_PATH: ${ARTIFACTORY_DOCKER_PATH_QGBOT}
        DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
        DOCKER_ADDITIONAL_TAG: mr-${CI_MERGE_REQUEST_IID}
        REPOSITORY: ${ARTIFACTORY_DOCKER_TEST_REPOSITORY}
        DOCKERFILE_PATH: "python/Dockerfile"
      changes:
        paths:
          - python/**/*
          - infrastructure/**/*
  interruptible: true
  tags:
    - Linux
    - DockerExecutor

### CI template for scan docker images via trivy tool
.scan_template:
  image: "$CS_ANALYZER_IMAGE$CS_IMAGE_SUFFIX"
  stage: e2e-test
  variables:
    GIT_STRATEGY: none
    CS_ANALYZER_IMAGE: "$CI_TEMPLATE_REGISTRY_HOST/security-products/container-scanning:5"
    CS_SCHEMA_MODEL: 15
    CS_REGISTRY_USER: $ARTIFACTORY_USER
    CS_REGISTRY_PASSWORD: $ARTIFACTORY_PASS
  allow_failure: true
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
      dependency_scanning: gl-dependency-scanning-report.json
    paths:
      [ gl-container-scanning-report.json, gl-dependency-scanning-report.json ]
  dependencies: [ ]
  script:
    - gtcs scan
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_TEST_REPOSITORY}
    - if: $CI_COMMIT_TAG
      variables:
        DOCKER_TAG: ${CI_COMMIT_TAG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_DEV_REPOSITORY}
  tags:
    - AWS
    - DockerExecutor
  interruptible: true

### Scan frontend docker images. Run on git tag
container_scanning_frontend:
  extends: .scan_template
  variables:
    CS_IMAGE: $REPOSITORY/${ARTIFACTORY_DOCKER_PATH_FRONTEND}:$DOCKER_TAG
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - frontend/**/*
          - backend/parser/src/main/antlr/com/epam/deltix/quantgrid/parser/**/*
          - infrastructure/**/*
      variables:
        DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_TEST_REPOSITORY}
    - if: $CI_COMMIT_TAG
      variables:
        DOCKER_TAG: ${CI_COMMIT_TAG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_DEV_REPOSITORY}

### Scan backend docker images. Run on git tag
container_scanning_backend:
  extends: .scan_template
  variables:
    CS_IMAGE: $REPOSITORY/${ARTIFACTORY_DOCKER_PATH_BACKEND}:$DOCKER_TAG
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - backend/**/*
          - infrastructure/**/*
      variables:
        DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_TEST_REPOSITORY}
    - if: $CI_COMMIT_TAG
      variables:
        DOCKER_TAG: ${CI_COMMIT_TAG}
        REPOSITORY: ${ARTIFACTORY_DOCKER_DEV_REPOSITORY}

### Copy frontend and backend docker images to public repository. Run on git tag manually
promote:
  image: dockerhub.deltixhub.com/curlimages/curl:7.88.1
  stage: promote
  variables:
    GIT_STRATEGY: none
  script:
    - 'curl --retry 6 --retry-all-errors --no-progress-meter --fail -X POST "${ARTIFACTORY_URL}/api/docker/epm-rtc-docker/v2/promote" -H "Content-Type: application/json" -u${ARTIFACTORY_USER}:${ARTIFACTORY_PASS} -d ''{ "targetRepo": "epm-rtc-public-docker", "dockerRepository": "''"${ARTIFACTORY_DOCKER_PATH_FRONTEND}"''", "tag" : "''"$CI_COMMIT_TAG"''", "copy": true }'''
    - 'curl --retry 6 --retry-all-errors --no-progress-meter --fail -X POST "${ARTIFACTORY_URL}/api/docker/epm-rtc-docker/v2/promote" -H "Content-Type: application/json" -u${ARTIFACTORY_USER}:${ARTIFACTORY_PASS} -d ''{ "targetRepo": "epm-rtc-public-docker", "dockerRepository": "''"${ARTIFACTORY_DOCKER_PATH_BACKEND}"''", "tag" : "''"$CI_COMMIT_TAG"''", "copy": true }'''
    - 'curl --retry 6 --retry-all-errors --no-progress-meter --fail -X POST "${ARTIFACTORY_URL}/api/docker/epm-rtc-docker/v2/promote" -H "Content-Type: application/json" -u${ARTIFACTORY_USER}:${ARTIFACTORY_PASS} -d ''{ "targetRepo": "epm-rtc-public-docker", "dockerRepository": "''"${ARTIFACTORY_DOCKER_PATH_DESTINATION_DIAL}"''", "tag" : "''"$CI_COMMIT_TAG"''", "copy": true }'''
    - 'curl --retry 6 --retry-all-errors --no-progress-meter --fail -X POST "${ARTIFACTORY_URL}/api/docker/epm-rtc-docker/v2/promote" -H "Content-Type: application/json" -u${ARTIFACTORY_USER}:${ARTIFACTORY_PASS} -d ''{ "targetRepo": "epm-rtc-public-docker", "dockerRepository": "''"${ARTIFACTORY_DOCKER_PATH_SOURCE_DIAL}"''", "tag" : "''"$CI_COMMIT_TAG"''", "copy": true }'''
    - 'curl --retry 6 --retry-all-errors --no-progress-meter --fail -X POST "${ARTIFACTORY_URL}/api/docker/epm-rtc-docker/v2/promote" -H "Content-Type: application/json" -u${ARTIFACTORY_USER}:${ARTIFACTORY_PASS} -d ''{ "targetRepo": "epm-rtc-public-docker", "dockerRepository": "''"${ARTIFACTORY_DOCKER_PATH_QGBOT}"''", "tag" : "''"$CI_COMMIT_TAG"''", "copy": true }'''
  dependencies: [ ]
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
  interruptible: true
  tags:
    - AWS
    - DockerExecutor

### step required to copy qgbot test files from directory in root to dial review prefix folder
copy_integration_test_files_qgbot:
  image: registry.deltixhub.com/devops/kubernetes-tools-gcp:1.32.0
  stage: deploy
  # extends: .cloud-auth
  variables:
    DIAL_PREFIX: "ai-dial-xl-mr-${CI_MERGE_REQUEST_IID}"
    GOOGLE_REGION: "us-central1"
    GOOGLE_PROJECT: "hl2-epm-dial-test-t1iylu"
    GCP_WORKLOAD_IDENTITY_PROVIDER: "projects/771246914069/locations/global/workloadIdentityPools/test-gitlab-ci/providers/gitlab-ci-dial-xl"
    GCP_SERVICE_ACCOUNT: test-dial-xl-tests@hl2-epm-dial-test-t1iylu.iam.gserviceaccount.com
  id_tokens:
    GITLAB_OIDC_TOKEN_GCP:
      aud: https://iam.googleapis.com/$GCP_WORKLOAD_IDENTITY_PROVIDER
  before_script:
    - |
      #!/bin/bash

      echo "INFO: Authenticating to GCP"

      IS_CLOUD_CLI_AVAILABLE=$(command -v gcloud 2>&1 >/dev/null && echo "true" || echo "false")

      echo $IS_CLOUD_CLI_AVAILABLE 

      # Verify project is set
      if [[ -z "$GOOGLE_PROJECT" ]]; then
        echo "ERROR: Variable GOOGLE_PROJECT is required but not defined"
        exit 1
      fi

      # Check if application default credentials file exists
      if [[ -n "$GOOGLE_APPLICATION_CREDENTIALS" && -f "$GOOGLE_APPLICATION_CREDENTIALS" ]]; then
        echo "INFO: Application Default Credentials found. Using them..."
      else
        echo "INFO: No supported credentials found. Falling back to OIDC authentication..."
        if [[ -z "$GCP_SERVICE_ACCOUNT" || -z "$GCP_WORKLOAD_IDENTITY_PROVIDER" ]]; then
          echo "ERROR: Variables GCP_SERVICE_ACCOUNT and GCP_WORKLOAD_IDENTITY_PROVIDER are required but not defined"
          exit 1
        fi
        JOB_JWT_FILE=$(mktemp)
        echo ${GITLAB_OIDC_TOKEN_GCP} >$JOB_JWT_FILE
        GOOGLE_APPLICATION_CREDENTIALS=$(mktemp)
        # HACK: cli-less alternative to `gcloud iam workload-identity-pools create-cred-config`
        tee $GOOGLE_APPLICATION_CREDENTIALS <<EOF
      {
          "type": "external_account",
          "audience": "//iam.googleapis.com/$GCP_WORKLOAD_IDENTITY_PROVIDER",
          "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
          "token_url": "https://sts.googleapis.com/v1/token",
          "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/$GCP_SERVICE_ACCOUNT:generateAccessToken",
          "credential_source": {
              "file": "$JOB_JWT_FILE",
              "format": {
                  "type": "text"
              }
          }
      }
      EOF
        export GOOGLE_APPLICATION_CREDENTIALS
      fi

      echo $GOOGLE_APPLICATION_CREDENTIALS  

      if $IS_CLOUD_CLI_AVAILABLE; then
        gcloud auth login --cred-file="$GOOGLE_APPLICATION_CREDENTIALS" --quiet
        gcloud config set project "$GOOGLE_PROJECT" --quiet
        gcloud auth list --format json
      fi
      echo "INFO: Authenticating to GCP done"
  script:
    - gcloud storage cp -r gs://test-dial-xl-test/dial-xl-bot/*.* gs://test-dial/${DIAL_PREFIX}/Keys/first-API-key/files/test-resources
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
      allow_failure: true
      changes:
        paths:
          - python/**/*
          - infrastructure/**/*
          - backend/**/*
    - if: '$CI_PIPELINE_SOURCE == "web"'
  interruptible: true
  tags:
    - kubernetes
    - staging

integration_test_qgbot:
  extends: .template_test_qgbot
  variables:
    PYTEST_TEST_TYPE: "integration"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      variables:
        OVERRIDE_TEST__API-KEY: ${TEST_DIAL_API_KEY}

        OVERRIDE_ASSISTANT__URL__DIAL: ${REVIEW_DIAL_URL}
        OVERRIDE_ASSISTANT__URL__XL: ${REVIEW_URL}
      
      allow_failure: true
    - if: '$CI_PIPELINE_SOURCE  == "schedule"'
      variables:
        OVERRIDE_TEST__API-KEY: ${DEV_DIAL_API_KEY}

        OVERRIDE_ASSISTANT__URL__DIAL: https://core.aks.dev.dial.parts
        OVERRIDE_ASSISTANT__URL__XL: https://xl.aks.dev.dial.parts

      when: always
      allow_failure: true
    - if: '$CI_COMMIT_BRANCH  == "main"'
      variables:
        OVERRIDE_TEST__API-KEY: ${DEV_DIAL_API_KEY}

        OVERRIDE_ASSISTANT__URL__DIAL: https://core.aks.dev.dial.parts
        OVERRIDE_ASSISTANT__URL__XL: https://xl.aks.dev.dial.parts

      allow_failure: true
      changes:
        paths:
          - python/**/*
          - backend/**/*
          - infrastructure/**/*
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
      variables:
        OVERRIDE_TEST__API-KEY: ${TEST_DIAL_API_KEY}

        OVERRIDE_ASSISTANT__URL__DIAL: ${REVIEW_DIAL_URL}
        OVERRIDE_ASSISTANT__URL__XL: ${REVIEW_URL}

      allow_failure: true
      changes:
        paths:
          - backend/**/*
          - python/**/*
          - infrastructure/**/*

store_integration_test_qgbot_to_s3:
  needs: [ integration_test_qgbot ]
  extends: .store_test_results_to_s3_template
  variables:
    DIR_NAME: integration

business_test_qgbot:
  extends: .template_test_qgbot
  variables:
    PYTEST_TEST_TYPE: "business"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      variables:
        OVERRIDE_TEST__API-KEY: ${TEST_DIAL_API_KEY}

        OVERRIDE_ASSISTANT__URL__DIAL: ${REVIEW_DIAL_URL}
        OVERRIDE_ASSISTANT__URL__XL: ${REVIEW_URL}

      allow_failure: true
      when: manual
    - if: '$CI_PIPELINE_SOURCE  == "schedule"'
      variables:
        OVERRIDE_TEST__API-KEY: ${DEV_DIAL_API_KEY}

        OVERRIDE_ASSISTANT__URL__DIAL: https://core.aks.dev.dial.parts
        OVERRIDE_ASSISTANT__URL__XL: https://xl.aks.dev.dial.parts

      when: always
      allow_failure: true
    - if: '$CI_COMMIT_BRANCH  == "main"'
      variables:
        OVERRIDE_TEST__API-KEY: ${DEV_DIAL_API_KEY}

        OVERRIDE_ASSISTANT__URL__DIAL: https://core.aks.dev.dial.parts
        OVERRIDE_ASSISTANT__URL__XL: https://xl.aks.dev.dial.parts

      when: manual
      allow_failure: true
      changes:
        paths:
          - python/**/*
          - backend/**/*
          - infrastructure/**/*
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
      variables:
        OVERRIDE_TEST__API-KEY: ${TEST_DIAL_API_KEY}

        OVERRIDE_ASSISTANT__URL__DIAL: ${REVIEW_DIAL_URL}
        OVERRIDE_ASSISTANT__URL__XL: ${REVIEW_URL}

      when: manual
      allow_failure: true
      changes:
        paths:
          - python/**/*
          - backend/**/*
          - infrastructure/**/*

store_business_test_qgbot_to_s3:
  needs: [ business_test_qgbot ]
  extends: .store_test_results_to_s3_template
  variables:
    DIR_NAME: business
