if ($request_method = OPTIONS) {
    add_header Access-Control-Allow-Origin      $cors_allow_origin;
    add_header Vary                             "Origin";
    add_header Access-Control-Allow-Credentials "true";
    add_header Access-Control-Allow-Headers     $cors_allow_headers;
    add_header Access-Control-Allow-Methods     $cors_allow_methods;
    add_header Access-Control-Max-Age           86400;
    return 204;
}

if ($cors_allow_origin != "") {
    add_header Access-Control-Allow-Origin      $cors_allow_origin always;
    add_header Vary                             "Origin"           always;
    add_header Access-Control-Allow-Credentials "true"             always;
}
