apiVersion: v1
kind: Secret
metadata:
  name: !param name
  labels:
    purpose: !param purpose
    job-id: !param job_id
  annotations:
    cleanup/ttl-seconds: !param ttl
stringData:
  .config.json: !param config