export enum GridMenuItem {
  RenameTable = 'RenameTable',
  MoveTable = 'MoveTable',
  DeleteTable = 'DeleteTable',
  Delete = 'Delete',
  Column = 'Column',
  CreateDerivedTable = 'CreateDerivedTable',
  Index = 'Index',
  AddChart = 'AddChart',
  RenameColumn = 'RenameColumn',
  AddKey = 'AddKey',
  RemoveKey = 'RemoveKey',
  EditCell = 'EditCell',
  RemoveOverrideCell = 'RemoveOverrideCell',
  EditFormula = 'EditFormula',
  DeleteField = 'DeleteField',
  DeleteColumn = 'DeleteColumn',
  SwapLeft = 'SwapLeft',
  SwapRight = 'SwapRight',
  SwapTop = 'SwapTop',
  SwapBottom = 'SwapBottom',
}
