export enum ProjectMenuItems {
  CreateWorksheet = 'Create Worksheet',
  RenameProject = 'Rename Project',
  DeleteProject = 'Delete Project',
  selectWorksheet = 'Select Worksheet',
  renameWorksheet = 'Rename Worksheet',
  deleteWorksheet = 'Delete Worksheet',
  selectTable = 'Select Table',
  renameTable = 'Rename Table',
  deleteTable = 'Delete Table',
  moveTable = 'Move Table',
  cloneTable = 'Clone Table',
  insertEntity = 'Insert',
  createDerived = 'Create derived',
  convertToChart = 'Convert to chart',
  addChart = 'Add Chart',
  selectField = 'Select Field',
  editFormula = 'Edit Formula',
  renameField = 'Rename Field',
  addKey = 'Add key',
  deleteEntity = 'Delete',
  fieldActions = 'Field',
  orientation = 'Orientation',
  hide = 'Hide',
}
